### ISSUE TITLE
Tab with 404 opened by Firefox after background update

### ISSUE THREAD

**Issue by NeatNit** [freedomgamesdev/wikigg-redirect-extension#34]
**Describe the bug**
This happened a few minutes ago. I think the Firefox extension just updated in the background, suddenly a new tab opened with the URL `moz-extension://ad4b3246-ed78-4415-8102-4de320ce4b79/edge-listing-changes.html` and the error that it could not be found:

![image](https://github.com/freedomgamesdev/wikigg-redirect-extension/assets/2400026/1551b293-85c7-474a-9def-fbc3e92b5177)

(I moved the tab to a new window to take a clean screenshot)

**To Reproduce**
Not sure if this only happens after extension update or if you can recreate it with an extension reinstall.

**Expected behavior**
Either the new tab should show recent changes, or it shouldn't open at all.

**Additional info:**
- Firefox
- Not actually browsing any wiki or interacting with the extension

**Comment by Azekthi** [comment]
Corroborating, this happened to me too when I just launched my Firefox for the first time today.

![image](https://github.com/freedomgamesdev/wikigg-redirect-extension/assets/11371137/b2edee1b-e85b-4180-8622-43f2e000bd78)

**Comment by alex4401** [comment]
Uploaded fixed packages to AMO. I've accidentally built 1.6.7 with WIP changes targeting Edge... 🤦🏻‍♂️
