### ISSUE TITLE
Search result replacement doesn't function

### ISSUE THREAD

**Issue by ChildishGiant** [freedomgamesdev/wikigg-redirect-extension#74]
I think this is supposed to replace search results on google and duckduckgo but it doesn't seem to.
Firefox version: 124.0.1

![image](https://github.com/freedomgamesdev/wikigg-redirect-extension/assets/13716824/1804acbe-4443-44de-ae6e-d0c3c43a083a)
![image](https://github.com/freedomgamesdev/wikigg-redirect-extension/assets/13716824/773b5252-d9ec-41ac-936c-f84e6f1e700e)

**Comment by alex4401** [comment]
To get the Minecraft Wiki redirected, use Indie Wiki Buddy.

wiki.gg Redirect only covers wiki.gg wikis.
