### ISSUE TITLE
Minecraft.fandom.com not redirecting to minecraft.wiki

### ISSUE THREAD

**Issue by Tom1817** [freedomgamesdev/wikigg-redirect-extension#80]
**Describe the bug**
The plugin is not recognizing minecraft.fandom.com and so is not replacing it with minecraft.wiki

**To Reproduce**
1. google "minecraft wiki"

**Expected behavior**
The first result "https://minecraft.fandom.com/wiki/Minecraft_Wiki" should be replaced by "https://minecraft.wiki/"

**Additional info:**
- Firefox v127.0
- Minecraft wiki
- see https://www.reddit.com/r/Minecraft/comments/16r3y8x/the_minecraft_wiki_has_moved_from_fandom_to/

**Comment by RheingoldRiver** [comment]
Hi, this is the wiki.gg redirect extension, it only supports wiki.gg wikis. As the Minecraft wiki is not hosted on wiki.gg, please additionally use https://getindie.wiki/ to have MCW redirect

**Comment by Tom1817** [comment]
Ah my apologies, thank you for the pointer <3
