### ISSUE TITLE
Shadows of Abaddon (terraria mod) wiki

### ISSUE THREAD

**Issue by Lykrast** [freedomgamesdev/wikigg-redirect-extension#84]
**Is your feature request related to a problem? Please describe.**
A Terraria mod wiki that I did not notice was not in there.

**Describe the solution you'd like**
https://shadowsofabaddon.fandom.com/ -> https://shadowsofabaddon.wiki.gg/

**Additional context**
I don't know how to PR to submit wikis hope that's a good place.

**Comment by alex4401** [comment]
Thanks, will be added in the next version (today)
