### ISSUE TITLE
Add redirect for Epic Battle Fantasy wiki

### ISSUE THREAD

**Issue by eliana-bb** [freedomgamesdev/wikigg-redirect-extension#85]
As of February of 2024, the EBF wiki (https://epicbattlefantasy.fandom.com/wiki/Epic_Battle_Fantasy_Wiki) has been ported into wiki.gg (https://epicbattlefantasy.wiki.gg/wiki/Epic_Battle_Fantasy_Wiki)
I'd appreciate if you could add the redirect so the new wiki could get some more traction!

**Comment by alex4401** [comment]
Done, uploading update now
