### ISSUE TITLE
Firefox for Android support

### ISSUE THREAD

**Issue by Alshain01** [freedomgamesdev/wikigg-redirect-extension#9]
**Is your feature request related to a problem? Please describe.**
No, other than a lack of support, if that is a "problem".

**Describe the solution you'd like**
I'd like the plugin to be released for Firefox On Android if possible.

**Describe alternatives you've considered**
None that I've found.

**Additional context**
None.

**Extra information** (if applicable)
- Browser [e.g. chrome, firefox]: Firefox... For Android.
- Wiki [e.g. Temtem, ARK, Sea of Thieves] Several, Ark, Astroneer and others.

**Comment by alex4401** [comment]
Curiously, I've already marked the latest [and a few more] release as compatible with Android:
![image](https://github.com/alex4401/wikigg-redirect-extension/assets/33527044/4e501d80-7ec9-476b-a3cd-8d3276e35e33)

Guessing from this article, Mozilla only offers quite a limited subset of extensions on Android: https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/

I'll shoot them an e-mail but honestly I doubt much will come out of that.

**Comment by Alshain01** [comment]
Hmm, I see. Well thank you very much for trying anyway.  Hopefully someday they will loosen those restrictions.

**Comment by alex4401** [comment]
"Not planned now" is not the best status but the only other one offered by GitHub is "complete". I'll keep looking out for any news on the topic from Mozilla.

**Comment by alex4401** [comment]
On a second thought, this should stay open.

**Comment by KevinPayravi** [comment]
Until Firefox for Android gets full extension support, there's a workaround I give to people for Indie Wiki Buddy. Firefox Beta in developer mode lets users load add-on collections that contain any extension.

I wrote a guide here:
https://getindie.wiki/firefox-mobile/

It's obviously not ideal, but it's the best we've got as a stopgap.

**Comment by alex4401** [comment]
Thank you!

I went ahead and created a collection in case anyone will want to try that out: id: `17555792`, name: `Redirect-to-wiki-gg`

**Comment by KevinPayravi** [comment]
I've also created `Wiki-Redirectors` (ID `17671762`) that has both Redirect to Wiki.gg + Indie Wiki Buddy, for anyone who wants to run with both.

**Comment by KevinPayravi** [comment]
Excellent news from Mozilla:

> In the coming months Mozilla will launch support for an open ecosystem of extensions on Firefox for Android on addons.mozilla.org (AMO). We’ll announce a definite launch date in early September, but it’s safe to expect a roll-out before the year’s end.

https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/

**Comment by Poopooracoocoo** [comment]
I believe it'll only support MV3 extensions

**Comment by alex4401** [comment]
Guessing based [on the Extension Workshop site](https://extensionworkshop.com/documentation/develop/differences-between-desktop-and-android-extensions/), MV3 requirement doesn't seem to be the case.

**Comment by alex4401** [comment]
This is done, as add-ons have launched for Android in December.
